### ISSUE TITLE
Chromatic not reporting back status

### ISSUE THREAD

**Issue by dominicroessner** [chromaui/action#20]
We have some GitHub Actions workflow runs that don't have any visual changes. The chromatic build passes, but the status isn't updated on the pull request.

See screenshot below, the status for **ci/chromatic** is now stuck on **Expected — Waiting for status to be reported**.

```
      - uses: chromaui/action@v1
        with:
          appCode: ${{ secrets.CHROMATIC_APP_CODE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: master
          exitZeroOnChanges: True
```
![image](https://user-images.githubusercontent.com/45669990/75196629-40b6be00-5711-11ea-928d-cfc962a205c8.png)
