### ISSUE TITLE
Pass option to this action to run inside a certain directory.

### ISSUE THREAD

**Issue by isaac-martin** [chromaui/action#30]
Would love an option on this action to run the job inside a certain directory. 
```
defaults:
  run:
    working-directory: web
```

We have a mono repo with the below dir structure
```
cms
web
 .storybook
```

Github actions need to live in the root - so currently we cant use this action and have to manually run chromatic using the script in our `package.json`
I can implement this change if someone can point me in the right direction.

**Comment by ndelangen** [comment]
I'd be happy to assist you getting set up:

Want to schedule a meeting?
https://calendly.com/ndelangen/storybook

**Comment by browniefed** [comment]
Agreed. We have a monorepo.
Setting up Lerna is overkill and unnecessary. Would be great to scope a directory to run this in rather than root of the repo.

**Comment by robertrbairdii** [comment]
I'm running into the same issue due to the `package.json` not being in the root dir of my repo (we're running some sort of frankenstein monorepo currently, and the directory where we are building our storybook is about 4 levels deep from the root dir). I'm getting the same error message that was in #36. I'm running my storybook build command in a previous step of my workflow, and ideally just want to pass in the path of the storybook-static directory that is nested deeper in my repo for it to be uploaded to chromatic. I'm hoping the fix in #41 fixes this issue and allows the script to progress further and successfully upload the built files.

**Comment by ndelangen** [comment]
Looks like there's no need for a custom implementation for this, this is supported by github action platform:
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun

**Comment by heybenchen** [comment]
@ndelangen Unfortunately setting the default run `working-directory` only applies to `run` actions, not `uses` actions. 

I have a project where the structure is something like:
- root
  - client
  - server

If I set up the action like this:
```yaml
name: "Chromatic"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          yarn && yarn build
        working-directory: client
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

Then when I run the build, I get this error:
```
Run chromaui/action@v1

Chromatic CLI v5.1.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '******kobt'
Retrieving git information
Retrieved git information
    → Commit '0d784fc' on branch 'bc/chromatic'; found 1 baseline commit
Collecting Storybook metadata
    → Could not find a supported Storybook viewlayer package. Make sure one is installed.

  ✖ Failed to collect Storybook metadata
Could not find a supported Storybook viewlayer package. Make sure one is installed.
→ View the full stacktrace below

  If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
  You can also email the team at support@chromatic.com if chat is not an option.
```
