### ISSUE TITLE
`build` can be null, leading to "Cannot destructure property `webUrl` of 'undefined' or 'null'."

### ISSUE THREAD

**Issue by tmeasday** [chromaui/action#36]
https://github.com/chromaui/action/blob/release/v1/lib/main.js#L65 assumes `build` is defined when sometimes I guess it isn't.

https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/conversation/27253867621#part_id=comment-27253867621-5972291213

**Comment by ndelangen** [comment]
How could it be that `build` isn't defined @ghengeveld ?

**Comment by ndelangen** [comment]
I could add a safety net for the missing build, but I think it's a bug upstream in the cli. it should always have a build shouldn't it?

**Comment by cereallarceny** [comment]
I'm also having this same issue.

https://github.com/OpenMined/omui

```yml
name: Run Chromatic

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ./omui && yarn install
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: storybook:build
          exitZeroOnChanges: true
          exitOnceUploaded: true
```

**Comment by cereallarceny** [comment]
I also tried the following modification, but Storybook had a heap error and ran out of memory... story(book) of my life. 🙄 

```yml
name: Run Chromatic

on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ./omui && yarn install && yarn storybook:build
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: build-storybook
          exitZeroOnChanges: true
          exitOnceUploaded: true
```

**Comment by cereallarceny** [comment]
I actually wonder if for me it could be related to this: https://github.com/chromaui/action/issues/30

While I'm not using Lerna, I am executing this one directory deeper than root. Could that cause `build` to not exist because it cannot find the build?

**Comment by cereallarceny** [comment]
I tried the last config again after upgrading successfully to Storybook 6 - this time, since SB6 is much faster, I can build the storybook successfully in the checkout step. However, `storybookBuildDir` totally ignores the build from the previous step. And instead, using `buildScriptName` won't build. Either way, [I get an identical error](https://github.com/OpenMined/omui/runs/932618349?check_suite_focus=true):

```
Run chromaui/action@v1
  with:
    token: ***
    projectToken: ***
    storybookBuildDir: build-storybook
    exitZeroOnChanges: true
    exitOnceUploaded: true

Chromatic CLI v5.0.0
https://www.chromatic.com/docs/cli

/home/runner/work/omui/omui/package.json: ENOENT: no such file or directory, open '/home/runner/work/omui/omui/package.json'
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
##[error]TypeError: Cannot destructure property `webUrl` of 'undefined' or 'null'.
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:65:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async run (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:120:33)
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
```

Here's the config for reference:
```yml
name: Run Chromatic

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          cd ./omui && yarn install && yarn storybook:build
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: build-storybook
          exitZeroOnChanges: true
          exitOnceUploaded: true
```

And here's the package.json for reference:
```json
{
  "name": "omui",
  "description": "The OpenMined UI component system for usage in all our web applications",
  "author": "Patrick Cason <patrick@openmined.org>",
  "license": "Apache-2.0",
  "version": "0.1.0",
  "homepage": "https://omui.openmined.org",
  "bugs": "https://github.com/openmined/omui/issues",
  "repository": {
    "type": "git",
    "url": "https://github.com/openmined/omui.git"
  },
  "keywords": [
    "design system",
    "framer",
    "omui",
    "openmined",
    "ui"
  ],
  "main": "build/index.js",
  "module": "build/index.esm.js",
  "scripts": {
    "start": "yarn storybook:start",
    "storybook:start": "start-storybook -p 3000",
    "storybook:build": "build-storybook -c .storybook -o build-storybook",
    "storybook:deploy": "storybook-to-ghpages --out=build-storybook",
    "chromatic": "chromatic --project-token=o20nr5wgm5s -b storybook:build --exit-zero-on-changes",
    "build": "parcel build src/index.ts",
    "analyze": "yarn build && source-map-explorer build/index.esm.js",
    "lint": "eslint .",
    "lint:fix": "eslint --fix .",
    "format": "pretty-quick --staged"
  },
  "husky": {
    "hooks": {
      "pre-commit": "yarn run lint && yarn run format"
    }
  },
  "dependencies": {
    "@chakra-ui/core": "1.0.0-rc.0",
    "@chakra-ui/pin-input": "1.0.0-rc.0",
    "@chakra-ui/system": "1.0.0-rc.0",
    "@chakra-ui/theme": "1.0.0-rc.0",
    "@chakra-ui/theme-tools": "1.0.0-rc.0",
    "prism-react-renderer": "^1.1.1",
    "react-simple-code-editor": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "7.10.4",
    "@chakra-ui/icons": "1.0.0-rc.0",
    "@parcel/transformer-typescript-tsc": "^2.0.0-beta.1",
    "@storybook/addon-docs": "^6.0.0-rc.20",
    "@storybook/addon-knobs": "^6.0.0-rc.20",
    "@storybook/addon-links": "^6.0.0-rc.20",
    "@storybook/addon-storysource": "^6.0.0-rc.20",
    "@storybook/addon-viewport": "^6.0.0-rc.20",
    "@storybook/react": "^6.0.0-rc.20",
    "@storybook/storybook-deployer": "^2.8.6",
    "@storybook/theming": "^6.0.0-rc.20",
    "@types/react": "16.9.41",
    "@types/react-dom": "^16.9.8",
    "@typescript-eslint/eslint-plugin": "^3.4.0",
    "@typescript-eslint/parser": "^3.4.0",
    "babel-eslint": "10.1.0",
    "babel-loader": "^8.1.0",
    "chromatic": "^5.0.0",
    "eslint": "7.3.1",
    "eslint-plugin-jest-dom": "^3.0.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.3",
    "eslint-plugin-react-hooks": "^4.0.5",
    "eslint-plugin-testing-library": "^3.3.1",
    "husky": "^4.2.5",
    "parcel": "^2.0.0-beta.1",
    "prettier": "^2.0.5",
    "pretty-quick": "^2.0.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-icons": "^3.10.0",
    "source-map-explorer": "^2.4.2",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.5"
  },
  "peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }
}
```

@ndelangen @ghengeveld Any help would be appreciated. It also looks like a duplicate issue has been created for this same problem: https://github.com/chromaui/action/issues/37

**Comment by mrlubos** [comment]
Hey all, in my case, this error was due to using a custom output directory in the `build-storybook` command. For context, instead of inlining the `build-storybook` command in `package.json`, I execute it as a part of Node script and there I define a custom output directory.

When I run `npx chromatic --build-script-name=my-custom-script`, it successfully builds and deploys, although it shows this warning.

```sh
⚠ Unexpected build directory
The CLI tried to build your Storybook at /var/folders/chromatic/stuff
but instead it was built at /some/other/path
Make sure your "my-custom-script" script forwards the --output-dir (-o) flag to the build-storybook CLI.
```

This is a plain warning and it doesn't crash the build, but simply translating this process into `chromaui/action@v1` doesn't work.

```yaml
# in Github Actions
- uses: chromaui/action@v1
  with:
    buildScriptName: my-custom-script
    projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    token: ${{ secrets.GITHUB_TOKEN }}
```

The CI will throw the error mentioned in this issue. The solution for me was to update `my-custom-script` to allow overriding the `--output-dir` flag and pass it to `build-storybook`.

**Comment by mrinalini-m** [comment]
I'm having the same error. I mentioned in #40 , renaming of the two tsconfig files that were present fixed the issue but only once. We don't have custom build scripts and the build directory is default. 

Right now, building locally works, deploying manually from CLI with chromatic still works too (chromatic version is **5.1.0**, storybook is 6.0.1x).

**Comment by ImranAhmed** [comment]
Seeing this also in a standard NextJS project with `Strorybook ^6.0.18`.

```
name: Run Chromatic

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: chromaui/action@v1
              with:
                  token: ${{ secrets.CHROMATIC_ACCESS_TOKEN }}
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  buildScriptName: build-storybook
                  exitZeroOnChanges: true
                  exitOnceUploaded: true
```
```
TypeError: Cannot destructure property `webUrl` of 'undefined' or 'null'.
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:65:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async run (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:120:33)
```

Any clues on solution? Thanks.
