### ISSUE TITLE
Add skip flag

### ISSUE THREAD

**Issue by code-mattclaffey** [chromaui/action#38]
Hello,

In the docs it states that you can add a `--skip` flag on the cli command but there is no way of being able to pass that on to the chromatic command. 

Why?

Dependabot has a high risk of abusing the snapshots so for our use cause we wish to be able to ignore it so it only tests our features.

Suggestion:

```
uses: chromaui/action@v1
with:
  token: ${{ secrets.GHP_TOKEN }}
  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
  skip: "dependabot/**"
```

May even be better to be just an options property.

**Comment by kylepeeler** [comment]
This is also a blocker for us using this action, please add this!

**Comment by kylepeeler** [comment]
Here is a workaround I used to prevent chromatic from running on Dependabot commits until this is implemented as a top-level action parameter: 

```yml
name: 'Chromatic'
on: push

jobs:
  chromatic:
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' # ignore the pull request which comes from user depbot.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Required to retrieve git history
          fetch-depth: 0
          # needed so we can pull other private npm dependencies, secrets.GITHUB_TOKEN is scoped to this repo only
          token: ${{ secrets.GitHubPAT }}
      - name: install dependencies
        run: npm ci
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # needed so we can pull other private npm dependencies, secrets.GITHUB_TOKEN is scoped to this repo only
          token: ${{ secrets.GitHubPAT }}
```
