### ISSUE TITLE
exitZeroOnChanges: false doesn't exit with 1

### ISSUE THREAD

**Issue by kylesuss** [chromaui/action#39]
I got a report of this on support. If I set `exitZeroOnChanges` to `false`, the action seems to actually exit with 0, showcased by the fact that my build is green on GitHub.

Here is an example commit where I introduce this behavior:

https://github.com/storybookjs/design-system/pull/202/files

And here is the subsequent build:

https://github.com/storybookjs/design-system/pull/202/checks?check_run_id=986230744

**Comment by emiloberg** [comment]
I'm the original reporter. Let me know if I can be of any help debugging/testing/etc.

**Comment by emiloberg** [comment]
Though about this a bit more. Are there any benefits of running this action instead of letting Github run the CLI command? It looks like the CLI is exiting with a non-zero exit code as it should.

E.g.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Upload to Chromatic
      run: node ./node_modules/.bin/chromatic --project-token=abc
```
