### ISSUE TITLE
"Failed to verify your Storybook", "Cannot destructure property `webUrl` of 'undefined' or 'null" after upgrading storybook 5.3.19 --> 6.0.7

### ISSUE THREAD

**Issue by mrinalini-m** [chromaui/action#40]
Was working with storybook v5.3.19 but it's failing after upgrading to v6.0.7.

![Screen Shot 2020-08-14 at 4 53 28 PM](https://user-images.githubusercontent.com/3789040/90300351-f48e4000-de4e-11ea-9f66-5be4536f3b03.png)

`chromatic.yml`:
```yml
# .github/workflows/chromatic.yml
# name of our action
name: "Chromatic Deployment"
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        # options required to the GitHub chromatic action
        with:
          # our project token, to see how to obtain it
          # refer to https://www.learnstorybook.com/intro-to-storybook/react/en/deploy/
          projectToken: ${{ secrets.CHROMATIC }}
```
Complete log:
```
Chromatic CLI v5.0.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '*******83e6'
Retrieving git information
Retrieved git information
    → Commit 'fb354f6' on branch 'storybook-upgrade'; found 1 baseline commit
Collecting Storybook metadata
Collected Storybook metadata
    → Storybook v6.0.7 for React; supported addons found: Actions, Backgrounds, Docs, Links, Storyshots, Viewport
Building your Storybook
    → Running command: build-storybook -- --output-dir /tmp/chromatic-2542jFJ3xjfp4pK1
Storybook built in 14 seconds
    → View build log at /home/runner/work/web-components/web-components/build-storybook.log
Publishing your built Storybook
    → Retrieving target location
    → Starting publish
Publish complete in 2 seconds
    → View your Storybook at https://5f276a74299f2d00222eb6d8-qnrpqiccfm.chromatic.com
Verifying your Storybook
    → This may take a few minutes
    → Failed to connect to https://5f276a74299f2d00222eb6d8-qnrpqiccfm.chromatic.com/iframe.html
     ✖ Failed to verify your Storybook
Failed to connect to https://5f276a74299f2d00222eb6d8-qnrpqiccfm.chromatic.com/iframe.html

  If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
  You can also email the team at support@chromatic.com if chat is not an option.

  Please provide us with the following info:
  {
"timestamp": "2020-08-14T22:58:47.806Z",
"sessionId": "a315354f-2173-4a06-9946-48a587e64871",
"gitVersion": "2.28.0",
"nodePlatform": "linux",
"nodeVersion": "12.13.1",
"packageName": "chromatic",
"packageVersion": "5.0.0",
"storybook": {
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
  "version": "6.0.7",
##[error]TypeError: Cannot destructure property `webUrl` of 'undefined' or 'null'.
    at runChromatic (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:65:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async run (/home/runner/work/_actions/chromaui/action/v1/lib/main.js:120:33)
  "viewLayer": "react",
##[error]Cannot destructure property `webUrl` of 'undefined' or 'null'.
   "addons": [
    {
      "name": "actions",
      "packageName": "@storybook/addon-actions",
      "packageVersion": "6.0.7"
    },
    {
      "name": "backgrounds",
      "packageName": "@storybook/addon-backgrounds",
      "packageVersion": "6.0.7"
    },
    {
      "name": "docs",
      "packageName": "@storybook/addon-docs",
      "packageVersion": "6.0.7"
    },
    {
      "name": "links",
      "packageName": "@storybook/addon-links",
      "packageVersion": "6.0.7"
    },
    {
      "name": "storyshots",
      "packageName": "@storybook/addon-storyshots",
      "packageVersion": "6.0.7"
    },
    {
      "name": "viewport",
      "packageName": "@storybook/addon-viewport",
      "packageVersion": "6.0.7"
    }
  ]
},
"flags": {
  "projectToken": "***",
  "fromCI": true,
  "interactive": false,
  "exitZeroOnChanges": true,
  "exitOnceUploaded": false,
  "allowConsoleErrors": false
},
"errorType": "GraphQLError",
"errorMessage": "✖ Failed to verify your Storybook\nFailed to connect to https://5f276a74299f2d00222eb6d8-qnrpqiccfm.chromatic.com/iframe.html",
"isolatorUrl": "https://5f276a74299f2d00222eb6d8-qnrpqiccfm.chromatic.com/iframe.html"
}
```
