### ISSUE TITLE
Semantic versioning?

### ISSUE THREAD

**Issue by mrlubos** [chromaui/action#49]
Hey, can you please use semantic versioning on this project? Using the latest version from Github Actions looks like this

```yaml
- name: Chromatic Action
  uses: chromaui/action@v1
```

Using semantic versioning would prevent introducing breaking changes to people's builds. For example, you've just released a new version which introduced some breaking changes and causes my whole CI pipeline to fail.

The error I see in Github Actions

```
Run chromaui/action@v1
  with:
    buildScriptName: storybook-build
    exitOnceUploaded: true
    exitZeroOnChanges: true
    projectToken: ***
    token: ***

Chromatic CLI v5.1.0
https://www.chromatic.com/docs/cli

Cannot read property 'scripts' of undefined
##[error]non-zero exit code
```

This is my Github Action setup that used to work before the update

```yaml
- uses: chromaui/action@v1
   with:
     buildScriptName: storybook-build
     exitOnceUploaded: true
     exitZeroOnChanges: true
     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
     token: ${{ secrets.GITHUB_TOKEN }}
```

And `package.json`

```json
"storybook-build": "node ./scripts/storybook-build",
```
